/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LettuceButton {
        "fluid": boolean;
        "newGame": boolean;
        "sizeSelection": string | 'sm' | 'md' | 'lg';
        "square": boolean;
        "text": string;
        "type": string;
    }
    interface LettucePageContentContainer {
    }
    interface LettuceSpacingVertical {
        "sizeSelection": string;
    }
    interface LettuceSudokuBoard {
        "currentBoard": string;
        "initialBoard": string;
        "order": number;
        "selectedCol": number;
        "selectedRow": number;
    }
    interface LettuceSudokuCell {
        "col": number;
        "number": number;
        "numberStatus": string;
        "row": number;
        "selectionState": string;
        "type": string;
    }
    interface LettuceSudokuGame {
        "order": number;
    }
    interface LettuceSudokuMoveButtons {
        "order": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLettuceButtonElement extends Components.LettuceButton, HTMLStencilElement {
    }
    var HTMLLettuceButtonElement: {
        prototype: HTMLLettuceButtonElement;
        new (): HTMLLettuceButtonElement;
    };
    interface HTMLLettucePageContentContainerElement extends Components.LettucePageContentContainer, HTMLStencilElement {
    }
    var HTMLLettucePageContentContainerElement: {
        prototype: HTMLLettucePageContentContainerElement;
        new (): HTMLLettucePageContentContainerElement;
    };
    interface HTMLLettuceSpacingVerticalElement extends Components.LettuceSpacingVertical, HTMLStencilElement {
    }
    var HTMLLettuceSpacingVerticalElement: {
        prototype: HTMLLettuceSpacingVerticalElement;
        new (): HTMLLettuceSpacingVerticalElement;
    };
    interface HTMLLettuceSudokuBoardElement extends Components.LettuceSudokuBoard, HTMLStencilElement {
    }
    var HTMLLettuceSudokuBoardElement: {
        prototype: HTMLLettuceSudokuBoardElement;
        new (): HTMLLettuceSudokuBoardElement;
    };
    interface HTMLLettuceSudokuCellElement extends Components.LettuceSudokuCell, HTMLStencilElement {
    }
    var HTMLLettuceSudokuCellElement: {
        prototype: HTMLLettuceSudokuCellElement;
        new (): HTMLLettuceSudokuCellElement;
    };
    interface HTMLLettuceSudokuGameElement extends Components.LettuceSudokuGame, HTMLStencilElement {
    }
    var HTMLLettuceSudokuGameElement: {
        prototype: HTMLLettuceSudokuGameElement;
        new (): HTMLLettuceSudokuGameElement;
    };
    interface HTMLLettuceSudokuMoveButtonsElement extends Components.LettuceSudokuMoveButtons, HTMLStencilElement {
    }
    var HTMLLettuceSudokuMoveButtonsElement: {
        prototype: HTMLLettuceSudokuMoveButtonsElement;
        new (): HTMLLettuceSudokuMoveButtonsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "lettuce-button": HTMLLettuceButtonElement;
        "lettuce-page-content-container": HTMLLettucePageContentContainerElement;
        "lettuce-spacing-vertical": HTMLLettuceSpacingVerticalElement;
        "lettuce-sudoku-board": HTMLLettuceSudokuBoardElement;
        "lettuce-sudoku-cell": HTMLLettuceSudokuCellElement;
        "lettuce-sudoku-game": HTMLLettuceSudokuGameElement;
        "lettuce-sudoku-move-buttons": HTMLLettuceSudokuMoveButtonsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LettuceButton {
        "fluid"?: boolean;
        "newGame"?: boolean;
        "sizeSelection"?: string | 'sm' | 'md' | 'lg';
        "square"?: boolean;
        "text"?: string;
        "type"?: string;
    }
    interface LettucePageContentContainer {
    }
    interface LettuceSpacingVertical {
        "sizeSelection"?: string;
    }
    interface LettuceSudokuBoard {
        "currentBoard"?: string;
        "initialBoard"?: string;
        "order"?: number;
        "selectedCol"?: number;
        "selectedRow"?: number;
    }
    interface LettuceSudokuCell {
        "col"?: number;
        "number"?: number;
        "numberStatus"?: string;
        "onCellSelected"?: (event: CustomEvent<any>) => void;
        "row"?: number;
        "selectionState"?: string;
        "type"?: string;
    }
    interface LettuceSudokuGame {
        "onMoveEvent"?: (event: CustomEvent<any>) => void;
        "onNewGameEvent"?: (event: CustomEvent<any>) => void;
        "order"?: number;
    }
    interface LettuceSudokuMoveButtons {
        "onMoveEvent"?: (event: CustomEvent<any>) => void;
        "order"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "lettuce-button": LettuceButton;
        "lettuce-page-content-container": LettucePageContentContainer;
        "lettuce-spacing-vertical": LettuceSpacingVertical;
        "lettuce-sudoku-board": LettuceSudokuBoard;
        "lettuce-sudoku-cell": LettuceSudokuCell;
        "lettuce-sudoku-game": LettuceSudokuGame;
        "lettuce-sudoku-move-buttons": LettuceSudokuMoveButtons;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lettuce-button": LocalJSX.LettuceButton & JSXBase.HTMLAttributes<HTMLLettuceButtonElement>;
            "lettuce-page-content-container": LocalJSX.LettucePageContentContainer & JSXBase.HTMLAttributes<HTMLLettucePageContentContainerElement>;
            "lettuce-spacing-vertical": LocalJSX.LettuceSpacingVertical & JSXBase.HTMLAttributes<HTMLLettuceSpacingVerticalElement>;
            "lettuce-sudoku-board": LocalJSX.LettuceSudokuBoard & JSXBase.HTMLAttributes<HTMLLettuceSudokuBoardElement>;
            "lettuce-sudoku-cell": LocalJSX.LettuceSudokuCell & JSXBase.HTMLAttributes<HTMLLettuceSudokuCellElement>;
            "lettuce-sudoku-game": LocalJSX.LettuceSudokuGame & JSXBase.HTMLAttributes<HTMLLettuceSudokuGameElement>;
            "lettuce-sudoku-move-buttons": LocalJSX.LettuceSudokuMoveButtons & JSXBase.HTMLAttributes<HTMLLettuceSudokuMoveButtonsElement>;
        }
    }
}
